"""Files

Revision ID: 95399d2ddc96
Revises: 8e5db300ef8c
Create Date: 2026-08-03 12:17:54.285293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95399d2ddc96'
down_revision = '8e5db300ef8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('files'):
        op.create_table('files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=True),
        sa.Column('extension', sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    coches_columns = [column['name'] for column in inspector.get_columns('coches')]
    if 'document_id' not in coches_columns:
        with op.batch_alter_table('coches', schema=None) as batch_op:
            batch_op.add_column(sa.Column('document_id', sa.Integer(), nullable=True))

    inspector = sa.inspect(bind)
    foreign_keys = inspector.get_foreign_keys('coches')
    if not any(
        fk.get('constrained_columns') == ['document_id'] and fk.get('referred_table') == 'files'
        for fk in foreign_keys
    ):
        with op.batch_alter_table('coches', schema=None) as batch_op:
            batch_op.create_foreign_key(
                'fk_coches_document_id_files',
                'files',
                ['document_id'],
                ['id']
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table('coches'):
        foreign_keys = inspector.get_foreign_keys('coches')
        if any(
            fk.get('name') == 'fk_coches_document_id_files' for fk in foreign_keys
        ):
            with op.batch_alter_table('coches', schema=None) as batch_op:
                batch_op.drop_constraint('fk_coches_document_id_files', type_='foreignkey')

        coches_columns = [column['name'] for column in inspector.get_columns('coches')]
        if 'document_id' in coches_columns:
            with op.batch_alter_table('coches', schema=None) as batch_op:
                batch_op.drop_column('document_id')

    if inspector.has_table('files'):
        op.drop_table('files')
    # ### end Alembic commands ###
