"""brands

Revision ID: b5b866962176
Revises: 95399d2ddc96
Create Date: 2026-08-24 16:05:02.522685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b866962176'
down_revision = '95399d2ddc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('brands'):
        op.create_table('brands',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    inspector = sa.inspect(bind)
    coches_columns = [column['name'] for column in inspector.get_columns('coches')]
    if 'brand_id' not in coches_columns:
        with op.batch_alter_table('coches', schema=None) as batch_op:
            batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))

    inspector = sa.inspect(bind)
    foreign_keys = inspector.get_foreign_keys('coches')
    if not any(
        fk.get('constrained_columns') == ['brand_id'] and fk.get('referred_table') == 'brands'
        for fk in foreign_keys
    ):
        with op.batch_alter_table('coches', schema=None) as batch_op:
            batch_op.create_foreign_key(
                'fk_coches_brand_id_brands',
                'brands',
                ['brand_id'],
                ['id']
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('brand_id')

    op.drop_table('brands')
    # ### end Alembic commands ###
